server:
  port: 8088
  tomcat:
    uri-encoding: utf-8
  max-http-header-size: 80KB
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodie?useSSL=false&&useUnicode=true&characterEncoding=UTF-8&autoReconnect
    username: root
    password: root
    hikari:
      connection-timeout: 30000 #等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ
      minimum-idle: 5 # 最小连接数 m
      aximum-pool-size: 20 # 最大连接数
      auto-commit: true # 自动提交
      idle-timeout: 600000 # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP # 连接池名字
      max-lifetime: 1800000 # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
      connection-test-query: SELECT 1
  redis:
    # redis 单机单个实例
#    database: 1  # 使用的数据库（redis 默认有16个库 0-15） 我们这里使用的1
#    host:  43.128.169.198   # 你redis的地址 如果是再本地那就是localhost
#    port:  6379  # redis的端口号  默认6379 如果你改过就是是改动的端口
#    password:  root   # 如果redis 设置过密码就写密码 没有密码就不要写password
  # redis 哨兵
      database: 1
      password:  root
      sentinel:
        master: root-mymaster
        nodes: 192.168.133.111:26379,192.168.133.131:26379,192.168.133.132:26379,192.168.133.133:26379
  servlet:
    multipart:
      max-file-size: 512000  # 文件上传大小限制为 500k
      max-request-size: 512000  # 请求大小限制为 500k
mybatis:
  type-aliases-package: com.joeworld.pojo # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml # mapper映射文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
